services:
  postgres:
    image: postgres:18
    container_name: url-shortener
    restart: unless-stopped
    environment:
      POSTGRES_DB: url
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: