spring.application.name=UrlShortener


spring.datasource.url=jdbc:postgresql://<ip>:<port>/<dbname>
spring.datasource.username=<username>
spring.datasource.password=<password>

# TODO: Temporary Solution, add flyway migration later
spring.jpa.generate-ddl=true