CREATE TABLE short_links (
    id bigint generated by default as identity primary key,
    short_code varchar(8) not null unique,
    main_url text not null,
    user_id bigint not null,
    created_at timestamp not null default current_timestamp
);

CREATE INDEX idx_short_links_user_id
ON short_links(user_id);