CREATE TABLE short_links
(
    id         bigint generated by default as identity primary key,
    short_code varchar(8)  not null unique,
    main_url   text        not null,
    username   VARCHAR(50) not null,
    created_at timestamp   not null default current_timestamp
);

CREATE INDEX idx_short_links_user_created
    ON short_links (username, created_at desc);